export const LOAD_MOVIES_LOADING = 'REDUX-THUNK-LOAD MOVIES-LOADING';
export const LOAD_MOVIES_SUCCESS = 'REDUX-THUNK-LOAD MOVIES-SUCCESS';
export const LOAD_MOVIES_ERROR = 'REDUX-THUNK-LOAD MOVIES-ERROR';